'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.service.objectdetection.v1.object_detection_grpc import (
    ObjectDetectionServiceBase,
    ObjectDetectionServiceStub
)
from .....gen.proto.api.service.objectdetection.v1.object_detection_pb2 import (
    AddDetectorRequest,
    AddDetectorResponse,
    DetectorNamesRequest,
    DetectorNamesResponse
)

__all__ = [
    'ObjectDetectionServiceBase',
    'ObjectDetectionServiceStub',
    'AddDetectorRequest',
    'AddDetectorResponse',
    'DetectorNamesRequest',
    'DetectorNamesResponse',
]
