'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.component.posetracker.v1.pose_tracker_grpc import (
    PoseTrackerServiceBase,
    PoseTrackerServiceStub
)
from .....gen.proto.api.component.posetracker.v1.pose_tracker_pb2 import (
    GetPosesRequest,
    GetPosesResponse
)

__all__ = [
    'PoseTrackerServiceBase',
    'PoseTrackerServiceStub',
    'GetPosesRequest',
    'GetPosesResponse',
]
