"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.posetracker.v1.pose_tracker_grpc import (
    PoseTrackerServiceBase,
    PoseTrackerServiceStub,
    UnimplementedPoseTrackerServiceBase,
)
from ....gen.component.posetracker.v1.pose_tracker_pb2 import GetPosesRequest, GetPosesResponse

__all__ = [
    "PoseTrackerServiceBase",
    "PoseTrackerServiceStub",
    "UnimplementedPoseTrackerServiceBase",
    "GetPosesRequest",
    "GetPosesResponse",
]
