"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.posetracker.v1.pose_tracker_unimplemented_grpc import UnimplementedPoseTrackerServiceBase

__all__ = [
    "UnimplementedPoseTrackerServiceBase",
]
