"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.vision.v1.vision_grpc import UnimplementedVisionServiceBase, VisionServiceBase, VisionServiceStub
from ....gen.service.vision.v1.vision_pb2 import (
    Classification,
    Detection,
    GetClassificationsFromCameraRequest,
    GetClassificationsFromCameraResponse,
    GetClassificationsRequest,
    GetClassificationsResponse,
    GetDetectionsFromCameraRequest,
    GetDetectionsFromCameraResponse,
    GetDetectionsRequest,
    GetDetectionsResponse,
    GetObjectPointCloudsRequest,
    GetObjectPointCloudsResponse,
)

__all__ = [
    "UnimplementedVisionServiceBase",
    "VisionServiceBase",
    "VisionServiceStub",
    "Classification",
    "Detection",
    "GetClassificationsFromCameraRequest",
    "GetClassificationsFromCameraResponse",
    "GetClassificationsRequest",
    "GetClassificationsResponse",
    "GetDetectionsFromCameraRequest",
    "GetDetectionsFromCameraResponse",
    "GetDetectionsRequest",
    "GetDetectionsResponse",
    "GetObjectPointCloudsRequest",
    "GetObjectPointCloudsResponse",
]
