"""
@generated by Viam.
Do not edit manually!
"""

from ....gen.service.vision.v1.vision_grpc import UnimplementedVisionServiceBase, VisionServiceBase, VisionServiceStub
from ....gen.service.vision.v1.vision_pb2 import (
    CaptureAllFromCameraRequest,
    CaptureAllFromCameraResponse,
    Classification,
    Detection,
    Detection3D,
    GetClassificationsFromCameraRequest,
    GetClassificationsFromCameraResponse,
    GetClassificationsRequest,
    GetClassificationsResponse,
    GetDetections3DRequest,
    GetDetections3DResponse,
    GetDetectionsFromCameraRequest,
    GetDetectionsFromCameraResponse,
    GetDetectionsRequest,
    GetDetectionsResponse,
    GetObjectPointCloudsRequest,
    GetObjectPointCloudsResponse,
    GetPropertiesRequest,
    GetPropertiesResponse,
)

__all__ = [
    "UnimplementedVisionServiceBase",
    "VisionServiceBase",
    "VisionServiceStub",
    "CaptureAllFromCameraRequest",
    "CaptureAllFromCameraResponse",
    "Classification",
    "Detection",
    "Detection3D",
    "GetClassificationsFromCameraRequest",
    "GetClassificationsFromCameraResponse",
    "GetClassificationsRequest",
    "GetClassificationsResponse",
    "GetDetections3DRequest",
    "GetDetections3DResponse",
    "GetDetectionsFromCameraRequest",
    "GetDetectionsFromCameraResponse",
    "GetDetectionsRequest",
    "GetDetectionsResponse",
    "GetObjectPointCloudsRequest",
    "GetObjectPointCloudsResponse",
    "GetPropertiesRequest",
    "GetPropertiesResponse",
]
