"""
@generated by Viam.
Do not edit manually!
"""
from .....gen.proto.rpc.examples.echo.v1.echo_unimplemented_grpc import UnimplementedEchoServiceBase

__all__ = [
    "UnimplementedEchoServiceBase",
]
