'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.component.arm.v1.arm_grpc import (
    ArmServiceBase,
    ArmServiceStub
)
from .....gen.proto.api.component.arm.v1.arm_pb2 import (
    GetEndPositionRequest,
    GetEndPositionResponse,
    GetJointPositionsRequest,
    GetJointPositionsResponse,
    JointPositions,
    MoveToJointPositionsRequest,
    MoveToJointPositionsResponse,
    MoveToPositionRequest,
    MoveToPositionResponse,
    Status,
    StopRequest,
    StopResponse
)

__all__ = [
    'ArmServiceBase',
    'ArmServiceStub',
    'GetEndPositionRequest',
    'GetEndPositionResponse',
    'GetJointPositionsRequest',
    'GetJointPositionsResponse',
    'JointPositions',
    'MoveToJointPositionsRequest',
    'MoveToJointPositionsResponse',
    'MoveToPositionRequest',
    'MoveToPositionResponse',
    'Status',
    'StopRequest',
    'StopResponse',
]
