"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.navigation.v1.navigation_grpc import NavigationServiceBase, NavigationServiceStub
from ....gen.service.navigation.v1.navigation_pb2 import (
    AddWaypointRequest,
    AddWaypointResponse,
    GetLocationRequest,
    GetLocationResponse,
    GetModeRequest,
    GetModeResponse,
    GetWaypointsRequest,
    GetWaypointsResponse,
    RemoveWaypointRequest,
    RemoveWaypointResponse,
    SetModeRequest,
    SetModeResponse,
    Waypoint,
)

__all__ = [
    "NavigationServiceBase",
    "NavigationServiceStub",
    "AddWaypointRequest",
    "AddWaypointResponse",
    "GetLocationRequest",
    "GetLocationResponse",
    "GetModeRequest",
    "GetModeResponse",
    "GetWaypointsRequest",
    "GetWaypointsResponse",
    "RemoveWaypointRequest",
    "RemoveWaypointResponse",
    "SetModeRequest",
    "SetModeResponse",
    "Waypoint",
]
