"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.navigation.v1.navigation_grpc import NavigationServiceBase, NavigationServiceStub
from ....gen.service.navigation.v1.navigation_pb2 import (
    AddWaypointRequest,
    AddWaypointResponse,
    GetLocationRequest,
    GetLocationResponse,
    GetModeRequest,
    GetModeResponse,
    GetObstaclesRequest,
    GetObstaclesResponse,
    GetPathsRequest,
    GetPathsResponse,
    GetPropertiesRequest,
    GetPropertiesResponse,
    GetWaypointsRequest,
    GetWaypointsResponse,
    MapType,
    Mode,
    Path,
    RemoveWaypointRequest,
    RemoveWaypointResponse,
    SetModeRequest,
    SetModeResponse,
    Waypoint,
)
from ....gen.service.navigation.v1.navigation_unimplemented_grpc import UnimplementedNavigationServiceBase

__all__ = [
    "NavigationServiceBase",
    "NavigationServiceStub",
    "AddWaypointRequest",
    "AddWaypointResponse",
    "GetLocationRequest",
    "GetLocationResponse",
    "GetModeRequest",
    "GetModeResponse",
    "GetObstaclesRequest",
    "GetObstaclesResponse",
    "GetPathsRequest",
    "GetPathsResponse",
    "GetPropertiesRequest",
    "GetPropertiesResponse",
    "GetWaypointsRequest",
    "GetWaypointsResponse",
    "MapType",
    "Mode",
    "Path",
    "RemoveWaypointRequest",
    "RemoveWaypointResponse",
    "SetModeRequest",
    "SetModeResponse",
    "Waypoint",
    "UnimplementedNavigationServiceBase",
]
