"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.navigation.v1.navigation_unimplemented_grpc import UnimplementedNavigationServiceBase

__all__ = [
    "UnimplementedNavigationServiceBase",
]
