'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.service.metadata.v1.metadata_grpc import (
    MetadataServiceBase,
    MetadataServiceStub
)
from .....gen.proto.api.service.metadata.v1.metadata_pb2 import (
    ResourcesRequest,
    ResourcesResponse
)

__all__ = [
    'MetadataServiceBase',
    'MetadataServiceStub',
    'ResourcesRequest',
    'ResourcesResponse',
]
