"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.app.mltraining.v1.ml_training_grpc import MLTrainingServiceBase, MLTrainingServiceStub
from ....gen.app.mltraining.v1.ml_training_pb2 import (
    CancelTrainingJobRequest,
    CancelTrainingJobResponse,
    DeleteCompletedTrainingJobRequest,
    DeleteCompletedTrainingJobResponse,
    GetTrainingJobRequest,
    GetTrainingJobResponse,
    ListTrainingJobsRequest,
    ListTrainingJobsResponse,
    ModelType,
    SubmitTrainingJobRequest,
    SubmitTrainingJobResponse,
    TrainingJobMetadata,
    TrainingStatus,
)

__all__ = [
    "MLTrainingServiceBase",
    "MLTrainingServiceStub",
    "CancelTrainingJobRequest",
    "CancelTrainingJobResponse",
    "DeleteCompletedTrainingJobRequest",
    "DeleteCompletedTrainingJobResponse",
    "GetTrainingJobRequest",
    "GetTrainingJobResponse",
    "ListTrainingJobsRequest",
    "ListTrainingJobsResponse",
    "ModelType",
    "SubmitTrainingJobRequest",
    "SubmitTrainingJobResponse",
    "TrainingJobMetadata",
    "TrainingStatus",
]
