"""
@generated by Viam.
Do not edit manually!
"""

from ....gen.app.mltraining.v1.ml_training_grpc import MLTrainingServiceBase, MLTrainingServiceStub, UnimplementedMLTrainingServiceBase
from ....gen.app.mltraining.v1.ml_training_pb2 import (
    CancelTrainingJobRequest,
    CancelTrainingJobResponse,
    Container,
    DeleteCompletedTrainingJobRequest,
    DeleteCompletedTrainingJobResponse,
    GetTrainingJobLogsRequest,
    GetTrainingJobLogsResponse,
    GetTrainingJobRequest,
    GetTrainingJobResponse,
    ListSupportedContainersRequest,
    ListSupportedContainersResponse,
    ListTrainingJobsRequest,
    ListTrainingJobsResponse,
    ModelFramework,
    ModelType,
    SubmitCustomTrainingJobRequest,
    SubmitCustomTrainingJobResponse,
    SubmitTrainingJobRequest,
    SubmitTrainingJobResponse,
    TrainingJobLogEntry,
    TrainingJobMetadata,
    TrainingStatus,
)

__all__ = [
    "MLTrainingServiceBase",
    "MLTrainingServiceStub",
    "UnimplementedMLTrainingServiceBase",
    "CancelTrainingJobRequest",
    "CancelTrainingJobResponse",
    "Container",
    "DeleteCompletedTrainingJobRequest",
    "DeleteCompletedTrainingJobResponse",
    "GetTrainingJobLogsRequest",
    "GetTrainingJobLogsResponse",
    "GetTrainingJobRequest",
    "GetTrainingJobResponse",
    "ListSupportedContainersRequest",
    "ListSupportedContainersResponse",
    "ListTrainingJobsRequest",
    "ListTrainingJobsResponse",
    "ModelFramework",
    "ModelType",
    "SubmitCustomTrainingJobRequest",
    "SubmitCustomTrainingJobResponse",
    "SubmitTrainingJobRequest",
    "SubmitTrainingJobResponse",
    "TrainingJobLogEntry",
    "TrainingJobMetadata",
    "TrainingStatus",
]
