"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.app.mltraining.v1.ml_training_unimplemented_grpc import UnimplementedMLTrainingServiceBase

__all__ = [
    "UnimplementedMLTrainingServiceBase",
]
