"""
@generated by Viam.
Do not edit manually!
"""

from ....gen.component.gripper.v1.gripper_grpc import GripperServiceBase, GripperServiceStub, UnimplementedGripperServiceBase
from ....gen.component.gripper.v1.gripper_pb2 import (
    GetCurrentInputsRequest,
    GetCurrentInputsResponse,
    GoToInputsRequest,
    GoToInputsResponse,
    GrabRequest,
    GrabResponse,
    IsHoldingSomethingRequest,
    IsHoldingSomethingResponse,
    IsMovingRequest,
    IsMovingResponse,
    OpenRequest,
    OpenResponse,
    StopRequest,
    StopResponse,
)

__all__ = [
    "GripperServiceBase",
    "GripperServiceStub",
    "UnimplementedGripperServiceBase",
    "GetCurrentInputsRequest",
    "GetCurrentInputsResponse",
    "GoToInputsRequest",
    "GoToInputsResponse",
    "GrabRequest",
    "GrabResponse",
    "IsHoldingSomethingRequest",
    "IsHoldingSomethingResponse",
    "IsMovingRequest",
    "IsMovingResponse",
    "OpenRequest",
    "OpenResponse",
    "StopRequest",
    "StopResponse",
]
