"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.gripper.v1.gripper_unimplemented_grpc import UnimplementedGripperServiceBase

__all__ = [
    "UnimplementedGripperServiceBase",
]
