"""
@generated by Viam.
Do not edit manually!
"""
from .....gen.proto.rpc.examples.fileupload.v1.fileupload_grpc import FileUploadServiceBase, FileUploadServiceStub
from .....gen.proto.rpc.examples.fileupload.v1.fileupload_pb2 import UploadFileRequest, UploadFileResponse

__all__ = [
    "FileUploadServiceBase",
    "FileUploadServiceStub",
    "UploadFileRequest",
    "UploadFileResponse",
]
