"""
@generated by Viam.
Do not edit manually!
"""
from .....gen.proto.rpc.examples.fileupload.v1.fileupload_unimplemented_grpc import UnimplementedFileUploadServiceBase

__all__ = [
    "UnimplementedFileUploadServiceBase",
]
