"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.app.datasync.v1.data_sync_unimplemented_grpc import UnimplementedDataSyncServiceBase

__all__ = [
    "UnimplementedDataSyncServiceBase",
]
