'''
@generated by Viam.
Do not edit manually!
'''
from ...gen.rpc.v1.auth_grpc import (
    AuthServiceBase,
    AuthServiceStub,
    ExternalAuthServiceBase,
    ExternalAuthServiceStub
)
from ...gen.rpc.v1.auth_pb2 import (
    AuthenticateRequest,
    AuthenticateResponse,
    AuthenticateToRequest,
    AuthenticateToResponse,
    Credentials
)

__all__ = [
    'AuthServiceBase',
    'AuthServiceStub',
    'ExternalAuthServiceBase',
    'ExternalAuthServiceStub',
    'AuthenticateRequest',
    'AuthenticateResponse',
    'AuthenticateToRequest',
    'AuthenticateToResponse',
    'Credentials',
]
