"""
@generated by Viam.
Do not edit manually!
"""
from ...gen.proto.rpc.v1.auth_unimplemented_grpc import UnimplementedAuthServiceBase, UnimplementedExternalAuthServiceBase

__all__ = [
    "UnimplementedAuthServiceBase",
    "UnimplementedExternalAuthServiceBase",
]
