"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.inputcontroller.v1.input_controller_unimplemented_grpc import UnimplementedInputControllerServiceBase

__all__ = [
    "UnimplementedInputControllerServiceBase",
]
