"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.shell.v1.shell_grpc import ShellServiceBase, ShellServiceStub, UnimplementedShellServiceBase
from ....gen.service.shell.v1.shell_pb2 import (
    CopyFilesFromMachineRequest,
    CopyFilesFromMachineRequestMetadata,
    CopyFilesFromMachineResponse,
    CopyFilesFromMachineResponseMetadata,
    CopyFilesSourceType,
    CopyFilesToMachineRequest,
    CopyFilesToMachineRequestMetadata,
    CopyFilesToMachineResponse,
    FileData,
    ShellRequest,
    ShellResponse,
)

__all__ = [
    "ShellServiceBase",
    "ShellServiceStub",
    "UnimplementedShellServiceBase",
    "CopyFilesFromMachineRequest",
    "CopyFilesFromMachineRequestMetadata",
    "CopyFilesFromMachineResponse",
    "CopyFilesFromMachineResponseMetadata",
    "CopyFilesSourceType",
    "CopyFilesToMachineRequest",
    "CopyFilesToMachineRequestMetadata",
    "CopyFilesToMachineResponse",
    "FileData",
    "ShellRequest",
    "ShellResponse",
]
