"""
@generated by Viam.
Do not edit manually!
"""
from .....gen.proto.api.component.generic.v1.generic_grpc import GenericServiceBase, GenericServiceStub
from .....gen.proto.api.component.generic.v1.generic_pb2 import DoRequest, DoResponse

__all__ = [
    "GenericServiceBase",
    "GenericServiceStub",
    "DoRequest",
    "DoResponse",
]
