"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.camera.v1.camera_grpc import CameraServiceBase, CameraServiceStub
from ....gen.component.camera.v1.camera_pb2 import (
    DistortionParameters,
    Format,
    GetImageRequest,
    GetImageResponse,
    GetImagesRequest,
    GetImagesResponse,
    GetPointCloudRequest,
    GetPointCloudResponse,
    GetPropertiesRequest,
    GetPropertiesResponse,
    Image,
    IntrinsicParameters,
    Property,
    RenderFrameRequest,
    Webcam,
    Webcams,
)

__all__ = [
    "CameraServiceBase",
    "CameraServiceStub",
    "DistortionParameters",
    "Format",
    "GetImageRequest",
    "GetImageResponse",
    "GetImagesRequest",
    "GetImagesResponse",
    "GetPointCloudRequest",
    "GetPointCloudResponse",
    "GetPropertiesRequest",
    "GetPropertiesResponse",
    "Image",
    "IntrinsicParameters",
    "Property",
    "RenderFrameRequest",
    "Webcam",
    "Webcams",
]
