"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.camera.v1.camera_unimplemented_grpc import UnimplementedCameraServiceBase

__all__ = [
    "UnimplementedCameraServiceBase",
]
