"""
@generated by Viam.
Do not edit manually!
"""
from .....gen.proto.api.service.vision.v1.vision_grpc import VisionServiceBase, VisionServiceStub
from .....gen.proto.api.service.vision.v1.vision_pb2 import (
    AddDetectorRequest,
    AddDetectorResponse,
    Detection,
    GetDetectionsRequest,
    GetDetectionsResponse,
    GetDetectorNamesRequest,
    GetDetectorNamesResponse,
    GetObjectPointCloudsRequest,
    GetObjectPointCloudsResponse,
    GetSegmenterNamesRequest,
    GetSegmenterNamesResponse,
    GetSegmenterParametersRequest,
    GetSegmenterParametersResponse,
    TypedParameter,
)

__all__ = [
    "VisionServiceBase",
    "VisionServiceStub",
    "AddDetectorRequest",
    "AddDetectorResponse",
    "Detection",
    "GetDetectionsRequest",
    "GetDetectionsResponse",
    "GetDetectorNamesRequest",
    "GetDetectorNamesResponse",
    "GetObjectPointCloudsRequest",
    "GetObjectPointCloudsResponse",
    "GetSegmenterNamesRequest",
    "GetSegmenterNamesResponse",
    "GetSegmenterParametersRequest",
    "GetSegmenterParametersResponse",
    "TypedParameter",
]
