"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import proto.api.common.v1.common_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ArmJointPositions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DEGREES_FIELD_NUMBER: builtins.int
    @property
    def degrees(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """A list of joint positions represented in degrees
        The numbers are ordered spatially from the base toward the end effector
        This is used in ArmServiceGetJointPositionsResponse and ArmServiceMoveToJointPositionsRequest
        """
        pass
    def __init__(self,
        *,
        degrees : typing.Optional[typing.Iterable[builtins.float]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["degrees",b"degrees"]) -> None: ...
global___ArmJointPositions = ArmJointPositions

class ArmServiceGetEndPositionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    """Name of an arm"""

    def __init__(self,
        *,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___ArmServiceGetEndPositionRequest = ArmServiceGetEndPositionRequest

class ArmServiceGetEndPositionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    POSE_FIELD_NUMBER: builtins.int
    @property
    def pose(self) -> proto.api.common.v1.common_pb2.Pose:
        """Returns 6d pose of the end effector relative to the base, represented by X,Y,Z coordinates which express
        millimeters and theta, ox, oy, oz coordinates which express an orientation vector
        """
        pass
    def __init__(self,
        *,
        pose : typing.Optional[proto.api.common.v1.common_pb2.Pose] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pose",b"pose"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pose",b"pose"]) -> None: ...
global___ArmServiceGetEndPositionResponse = ArmServiceGetEndPositionResponse

class ArmServiceGetJointPositionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    """Name of an arm"""

    def __init__(self,
        *,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___ArmServiceGetJointPositionsRequest = ArmServiceGetJointPositionsRequest

class ArmServiceGetJointPositionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    POSITION_DEGS_FIELD_NUMBER: builtins.int
    @property
    def position_degs(self) -> global___ArmJointPositions:
        """a list ArmJointPositions"""
        pass
    def __init__(self,
        *,
        position_degs : typing.Optional[global___ArmJointPositions] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["position_degs",b"position_degs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["position_degs",b"position_degs"]) -> None: ...
global___ArmServiceGetJointPositionsResponse = ArmServiceGetJointPositionsResponse

class ArmServiceMoveToPositionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    POSE_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    """Name of an arm"""

    @property
    def pose(self) -> proto.api.common.v1.common_pb2.Pose: ...
    def __init__(self,
        *,
        name : typing.Text = ...,
        pose : typing.Optional[proto.api.common.v1.common_pb2.Pose] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pose",b"pose"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","pose",b"pose"]) -> None: ...
global___ArmServiceMoveToPositionRequest = ArmServiceMoveToPositionRequest

class ArmServiceMoveToPositionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___ArmServiceMoveToPositionResponse = ArmServiceMoveToPositionResponse

class ArmServiceMoveToJointPositionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    POSITION_DEGS_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    """Name of an arm"""

    @property
    def position_degs(self) -> global___ArmJointPositions:
        """A list of joint positions represented in degrees
        There should be 1 entry in the list per joint, ordered spatially from the base toward the end effector
        """
        pass
    def __init__(self,
        *,
        name : typing.Text = ...,
        position_degs : typing.Optional[global___ArmJointPositions] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["position_degs",b"position_degs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","position_degs",b"position_degs"]) -> None: ...
global___ArmServiceMoveToJointPositionsRequest = ArmServiceMoveToJointPositionsRequest

class ArmServiceMoveToJointPositionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___ArmServiceMoveToJointPositionsResponse = ArmServiceMoveToJointPositionsResponse
