"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import proto.api.common.v1.common_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ArmJointPositions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DEGREES_FIELD_NUMBER: builtins.int
    @property
    def degrees(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """A list of joint positions represented in degrees
        The numbers are ordered spatially from the base toward the end effector
        This is used in ArmServiceCurrentJointPositionsResponse and ArmServiceMoveToJointPositionsRequest
        """
        pass
    def __init__(self,
        *,
        degrees : typing.Optional[typing.Iterable[builtins.float]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["degrees",b"degrees"]) -> None: ...
global___ArmJointPositions = ArmJointPositions

class ArmServiceCurrentPositionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    """Name of an arm"""

    def __init__(self,
        *,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___ArmServiceCurrentPositionRequest = ArmServiceCurrentPositionRequest

class ArmServiceCurrentPositionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    POSITION_FIELD_NUMBER: builtins.int
    @property
    def position(self) -> proto.api.common.v1.common_pb2.Pose:
        """Returns 6d pose of the end effector relative to the base, represented by X,Y,Z coordinates which express
        millimeters and theta, ox, oy, oz coordinates which express an orientation vector
        """
        pass
    def __init__(self,
        *,
        position : typing.Optional[proto.api.common.v1.common_pb2.Pose] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["position",b"position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["position",b"position"]) -> None: ...
global___ArmServiceCurrentPositionResponse = ArmServiceCurrentPositionResponse

class ArmServiceCurrentJointPositionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    """Name of an arm"""

    def __init__(self,
        *,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___ArmServiceCurrentJointPositionsRequest = ArmServiceCurrentJointPositionsRequest

class ArmServiceCurrentJointPositionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    POSITIONS_FIELD_NUMBER: builtins.int
    @property
    def positions(self) -> global___ArmJointPositions:
        """a list ArmJointPositions"""
        pass
    def __init__(self,
        *,
        positions : typing.Optional[global___ArmJointPositions] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["positions",b"positions"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["positions",b"positions"]) -> None: ...
global___ArmServiceCurrentJointPositionsResponse = ArmServiceCurrentJointPositionsResponse

class ArmServiceMoveToPositionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    TO_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    """Name of an arm"""

    @property
    def to(self) -> proto.api.common.v1.common_pb2.Pose: ...
    def __init__(self,
        *,
        name : typing.Text = ...,
        to : typing.Optional[proto.api.common.v1.common_pb2.Pose] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["to",b"to"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","to",b"to"]) -> None: ...
global___ArmServiceMoveToPositionRequest = ArmServiceMoveToPositionRequest

class ArmServiceMoveToPositionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___ArmServiceMoveToPositionResponse = ArmServiceMoveToPositionResponse

class ArmServiceMoveToJointPositionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    TO_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    """Name of an arm"""

    @property
    def to(self) -> global___ArmJointPositions:
        """A list of joint positions represented in degrees
        There should be 1 entry in the list per joint, ordered spatially from the base toward the end effector
        """
        pass
    def __init__(self,
        *,
        name : typing.Text = ...,
        to : typing.Optional[global___ArmJointPositions] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["to",b"to"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","to",b"to"]) -> None: ...
global___ArmServiceMoveToJointPositionsRequest = ArmServiceMoveToJointPositionsRequest

class ArmServiceMoveToJointPositionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___ArmServiceMoveToJointPositionsResponse = ArmServiceMoveToJointPositionsResponse

class ArmServiceJointMoveDeltaRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    JOINT_FIELD_NUMBER: builtins.int
    AMOUNT_DEGS_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    """Name of an arm"""

    joint: builtins.int = ...
    """To specify a joint, refer to base as 0 and count forwards up to the end effector"""

    amount_degs: builtins.float = ...
    """Specify degrees, can be positive or negative"""

    def __init__(self,
        *,
        name : typing.Text = ...,
        joint : builtins.int = ...,
        amount_degs : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount_degs",b"amount_degs","joint",b"joint","name",b"name"]) -> None: ...
global___ArmServiceJointMoveDeltaRequest = ArmServiceJointMoveDeltaRequest

class ArmServiceJointMoveDeltaResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___ArmServiceJointMoveDeltaResponse = ArmServiceJointMoveDeltaResponse
