# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: proto/api/component/v1/camera.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.api.annotations_pb2
import google.api.httpbody_pb2
import proto.api.common.v1.common_pb2
import proto.api.component.v1.camera_pb2


class CameraServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Frame(self, stream: 'grpclib.server.Stream[proto.api.component.v1.camera_pb2.CameraServiceFrameRequest, proto.api.component.v1.camera_pb2.CameraServiceFrameResponse]') -> None:
        pass

    @abc.abstractmethod
    async def RenderFrame(self, stream: 'grpclib.server.Stream[proto.api.component.v1.camera_pb2.CameraServiceRenderFrameRequest, google.api.httpbody_pb2.HttpBody]') -> None:
        pass

    @abc.abstractmethod
    async def PointCloud(self, stream: 'grpclib.server.Stream[proto.api.component.v1.camera_pb2.CameraServicePointCloudRequest, proto.api.component.v1.camera_pb2.CameraServicePointCloudResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ObjectPointClouds(self, stream: 'grpclib.server.Stream[proto.api.component.v1.camera_pb2.CameraServiceObjectPointCloudsRequest, proto.api.component.v1.camera_pb2.CameraServiceObjectPointCloudsResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/proto.api.component.v1.CameraService/Frame': grpclib.const.Handler(
                self.Frame,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.api.component.v1.camera_pb2.CameraServiceFrameRequest,
                proto.api.component.v1.camera_pb2.CameraServiceFrameResponse,
            ),
            '/proto.api.component.v1.CameraService/RenderFrame': grpclib.const.Handler(
                self.RenderFrame,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.api.component.v1.camera_pb2.CameraServiceRenderFrameRequest,
                google.api.httpbody_pb2.HttpBody,
            ),
            '/proto.api.component.v1.CameraService/PointCloud': grpclib.const.Handler(
                self.PointCloud,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.api.component.v1.camera_pb2.CameraServicePointCloudRequest,
                proto.api.component.v1.camera_pb2.CameraServicePointCloudResponse,
            ),
            '/proto.api.component.v1.CameraService/ObjectPointClouds': grpclib.const.Handler(
                self.ObjectPointClouds,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.api.component.v1.camera_pb2.CameraServiceObjectPointCloudsRequest,
                proto.api.component.v1.camera_pb2.CameraServiceObjectPointCloudsResponse,
            ),
        }


class CameraServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Frame = grpclib.client.UnaryUnaryMethod(
            channel,
            '/proto.api.component.v1.CameraService/Frame',
            proto.api.component.v1.camera_pb2.CameraServiceFrameRequest,
            proto.api.component.v1.camera_pb2.CameraServiceFrameResponse,
        )
        self.RenderFrame = grpclib.client.UnaryUnaryMethod(
            channel,
            '/proto.api.component.v1.CameraService/RenderFrame',
            proto.api.component.v1.camera_pb2.CameraServiceRenderFrameRequest,
            google.api.httpbody_pb2.HttpBody,
        )
        self.PointCloud = grpclib.client.UnaryUnaryMethod(
            channel,
            '/proto.api.component.v1.CameraService/PointCloud',
            proto.api.component.v1.camera_pb2.CameraServicePointCloudRequest,
            proto.api.component.v1.camera_pb2.CameraServicePointCloudResponse,
        )
        self.ObjectPointClouds = grpclib.client.UnaryUnaryMethod(
            channel,
            '/proto.api.component.v1.CameraService/ObjectPointClouds',
            proto.api.component.v1.camera_pb2.CameraServiceObjectPointCloudsRequest,
            proto.api.component.v1.camera_pb2.CameraServiceObjectPointCloudsResponse,
        )
