# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: proto/api/component/v1/gantry.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.api.annotations_pb2
import proto.api.component.v1.gantry_pb2


class GantryServiceBase(abc.ABC):

    @abc.abstractmethod
    async def CurrentPosition(self, stream: 'grpclib.server.Stream[proto.api.component.v1.gantry_pb2.GantryServiceCurrentPositionRequest, proto.api.component.v1.gantry_pb2.GantryServiceCurrentPositionResponse]') -> None:
        pass

    @abc.abstractmethod
    async def MoveToPosition(self, stream: 'grpclib.server.Stream[proto.api.component.v1.gantry_pb2.GantryServiceMoveToPositionRequest, proto.api.component.v1.gantry_pb2.GantryServiceMoveToPositionResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Lengths(self, stream: 'grpclib.server.Stream[proto.api.component.v1.gantry_pb2.GantryServiceLengthsRequest, proto.api.component.v1.gantry_pb2.GantryServiceLengthsResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/proto.api.component.v1.GantryService/CurrentPosition': grpclib.const.Handler(
                self.CurrentPosition,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.api.component.v1.gantry_pb2.GantryServiceCurrentPositionRequest,
                proto.api.component.v1.gantry_pb2.GantryServiceCurrentPositionResponse,
            ),
            '/proto.api.component.v1.GantryService/MoveToPosition': grpclib.const.Handler(
                self.MoveToPosition,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.api.component.v1.gantry_pb2.GantryServiceMoveToPositionRequest,
                proto.api.component.v1.gantry_pb2.GantryServiceMoveToPositionResponse,
            ),
            '/proto.api.component.v1.GantryService/Lengths': grpclib.const.Handler(
                self.Lengths,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.api.component.v1.gantry_pb2.GantryServiceLengthsRequest,
                proto.api.component.v1.gantry_pb2.GantryServiceLengthsResponse,
            ),
        }


class GantryServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.CurrentPosition = grpclib.client.UnaryUnaryMethod(
            channel,
            '/proto.api.component.v1.GantryService/CurrentPosition',
            proto.api.component.v1.gantry_pb2.GantryServiceCurrentPositionRequest,
            proto.api.component.v1.gantry_pb2.GantryServiceCurrentPositionResponse,
        )
        self.MoveToPosition = grpclib.client.UnaryUnaryMethod(
            channel,
            '/proto.api.component.v1.GantryService/MoveToPosition',
            proto.api.component.v1.gantry_pb2.GantryServiceMoveToPositionRequest,
            proto.api.component.v1.gantry_pb2.GantryServiceMoveToPositionResponse,
        )
        self.Lengths = grpclib.client.UnaryUnaryMethod(
            channel,
            '/proto.api.component.v1.GantryService/Lengths',
            proto.api.component.v1.gantry_pb2.GantryServiceLengthsRequest,
            proto.api.component.v1.gantry_pb2.GantryServiceLengthsResponse,
        )
