# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api/component/v1/imu.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n proto/api/component/v1/imu.proto\x12\x16proto.api.component.v1\x1a\x1cgoogle/api/annotations.proto\";\n\x0f\x41ngularVelocity\x12\x0c\n\x01x\x18\x01 \x01(\x01R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x01R\x01y\x12\x0c\n\x01z\x18\x03 \x01(\x01R\x01z\"I\n\x0b\x45ulerAngles\x12\x12\n\x04roll\x18\x01 \x01(\x01R\x04roll\x12\x14\n\x05pitch\x18\x02 \x01(\x01R\x05pitch\x12\x10\n\x03yaw\x18\x03 \x01(\x01R\x03yaw\"6\n IMUServiceAngularVelocityRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"w\n!IMUServiceAngularVelocityResponse\x12R\n\x10\x61ngular_velocity\x18\x01 \x01(\x0b\x32\'.proto.api.component.v1.AngularVelocityR\x0f\x61ngularVelocity\"2\n\x1cIMUServiceOrientationRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"f\n\x1dIMUServiceOrientationResponse\x12\x45\n\x0borientation\x18\x01 \x01(\x0b\x32#.proto.api.component.v1.EulerAnglesR\x0borientation2\xfb\x02\n\nIMUService\x12\xbd\x01\n\x0f\x41ngularVelocity\x12\x38.proto.api.component.v1.IMUServiceAngularVelocityRequest\x1a\x39.proto.api.component.v1.IMUServiceAngularVelocityResponse\"5\x82\xd3\xe4\x93\x02/\x12-/api/v1/component/imu/{name}/angular_velocity\x12\xac\x01\n\x0bOrientation\x12\x34.proto.api.component.v1.IMUServiceOrientationRequest\x1a\x35.proto.api.component.v1.IMUServiceOrientationResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/v1/component/imu/{name}/orientationBM\n#com.viam.rdk.proto.api.component.v1Z&go.viam.com/rdk/proto/api/component/v1b\x06proto3')



_ANGULARVELOCITY = DESCRIPTOR.message_types_by_name['AngularVelocity']
_EULERANGLES = DESCRIPTOR.message_types_by_name['EulerAngles']
_IMUSERVICEANGULARVELOCITYREQUEST = DESCRIPTOR.message_types_by_name['IMUServiceAngularVelocityRequest']
_IMUSERVICEANGULARVELOCITYRESPONSE = DESCRIPTOR.message_types_by_name['IMUServiceAngularVelocityResponse']
_IMUSERVICEORIENTATIONREQUEST = DESCRIPTOR.message_types_by_name['IMUServiceOrientationRequest']
_IMUSERVICEORIENTATIONRESPONSE = DESCRIPTOR.message_types_by_name['IMUServiceOrientationResponse']
AngularVelocity = _reflection.GeneratedProtocolMessageType('AngularVelocity', (_message.Message,), {
  'DESCRIPTOR' : _ANGULARVELOCITY,
  '__module__' : 'proto.api.component.v1.imu_pb2'
  # @@protoc_insertion_point(class_scope:proto.api.component.v1.AngularVelocity)
  })
_sym_db.RegisterMessage(AngularVelocity)

EulerAngles = _reflection.GeneratedProtocolMessageType('EulerAngles', (_message.Message,), {
  'DESCRIPTOR' : _EULERANGLES,
  '__module__' : 'proto.api.component.v1.imu_pb2'
  # @@protoc_insertion_point(class_scope:proto.api.component.v1.EulerAngles)
  })
_sym_db.RegisterMessage(EulerAngles)

IMUServiceAngularVelocityRequest = _reflection.GeneratedProtocolMessageType('IMUServiceAngularVelocityRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMUSERVICEANGULARVELOCITYREQUEST,
  '__module__' : 'proto.api.component.v1.imu_pb2'
  # @@protoc_insertion_point(class_scope:proto.api.component.v1.IMUServiceAngularVelocityRequest)
  })
_sym_db.RegisterMessage(IMUServiceAngularVelocityRequest)

IMUServiceAngularVelocityResponse = _reflection.GeneratedProtocolMessageType('IMUServiceAngularVelocityResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMUSERVICEANGULARVELOCITYRESPONSE,
  '__module__' : 'proto.api.component.v1.imu_pb2'
  # @@protoc_insertion_point(class_scope:proto.api.component.v1.IMUServiceAngularVelocityResponse)
  })
_sym_db.RegisterMessage(IMUServiceAngularVelocityResponse)

IMUServiceOrientationRequest = _reflection.GeneratedProtocolMessageType('IMUServiceOrientationRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMUSERVICEORIENTATIONREQUEST,
  '__module__' : 'proto.api.component.v1.imu_pb2'
  # @@protoc_insertion_point(class_scope:proto.api.component.v1.IMUServiceOrientationRequest)
  })
_sym_db.RegisterMessage(IMUServiceOrientationRequest)

IMUServiceOrientationResponse = _reflection.GeneratedProtocolMessageType('IMUServiceOrientationResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMUSERVICEORIENTATIONRESPONSE,
  '__module__' : 'proto.api.component.v1.imu_pb2'
  # @@protoc_insertion_point(class_scope:proto.api.component.v1.IMUServiceOrientationResponse)
  })
_sym_db.RegisterMessage(IMUServiceOrientationResponse)

_IMUSERVICE = DESCRIPTOR.services_by_name['IMUService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#com.viam.rdk.proto.api.component.v1Z&go.viam.com/rdk/proto/api/component/v1'
  _IMUSERVICE.methods_by_name['AngularVelocity']._options = None
  _IMUSERVICE.methods_by_name['AngularVelocity']._serialized_options = b'\202\323\344\223\002/\022-/api/v1/component/imu/{name}/angular_velocity'
  _IMUSERVICE.methods_by_name['Orientation']._options = None
  _IMUSERVICE.methods_by_name['Orientation']._serialized_options = b'\202\323\344\223\002*\022(/api/v1/component/imu/{name}/orientation'
  _ANGULARVELOCITY._serialized_start=90
  _ANGULARVELOCITY._serialized_end=149
  _EULERANGLES._serialized_start=151
  _EULERANGLES._serialized_end=224
  _IMUSERVICEANGULARVELOCITYREQUEST._serialized_start=226
  _IMUSERVICEANGULARVELOCITYREQUEST._serialized_end=280
  _IMUSERVICEANGULARVELOCITYRESPONSE._serialized_start=282
  _IMUSERVICEANGULARVELOCITYRESPONSE._serialized_end=401
  _IMUSERVICEORIENTATIONREQUEST._serialized_start=403
  _IMUSERVICEORIENTATIONREQUEST._serialized_end=453
  _IMUSERVICEORIENTATIONRESPONSE._serialized_start=455
  _IMUSERVICEORIENTATIONRESPONSE._serialized_end=557
  _IMUSERVICE._serialized_start=560
  _IMUSERVICE._serialized_end=939
# @@protoc_insertion_point(module_scope)
