# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: proto/api/component/v1/imu.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.api.annotations_pb2
import proto.api.component.v1.imu_pb2


class IMUServiceBase(abc.ABC):

    @abc.abstractmethod
    async def AngularVelocity(self, stream: 'grpclib.server.Stream[proto.api.component.v1.imu_pb2.IMUServiceAngularVelocityRequest, proto.api.component.v1.imu_pb2.IMUServiceAngularVelocityResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Orientation(self, stream: 'grpclib.server.Stream[proto.api.component.v1.imu_pb2.IMUServiceOrientationRequest, proto.api.component.v1.imu_pb2.IMUServiceOrientationResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/proto.api.component.v1.IMUService/AngularVelocity': grpclib.const.Handler(
                self.AngularVelocity,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.api.component.v1.imu_pb2.IMUServiceAngularVelocityRequest,
                proto.api.component.v1.imu_pb2.IMUServiceAngularVelocityResponse,
            ),
            '/proto.api.component.v1.IMUService/Orientation': grpclib.const.Handler(
                self.Orientation,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.api.component.v1.imu_pb2.IMUServiceOrientationRequest,
                proto.api.component.v1.imu_pb2.IMUServiceOrientationResponse,
            ),
        }


class IMUServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.AngularVelocity = grpclib.client.UnaryUnaryMethod(
            channel,
            '/proto.api.component.v1.IMUService/AngularVelocity',
            proto.api.component.v1.imu_pb2.IMUServiceAngularVelocityRequest,
            proto.api.component.v1.imu_pb2.IMUServiceAngularVelocityResponse,
        )
        self.Orientation = grpclib.client.UnaryUnaryMethod(
            channel,
            '/proto.api.component.v1.IMUService/Orientation',
            proto.api.component.v1.imu_pb2.IMUServiceOrientationRequest,
            proto.api.component.v1.imu_pb2.IMUServiceOrientationResponse,
        )
