"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.app.cloudslam.v1.cloud_slam_grpc import CloudSLAMServiceBase, CloudSLAMServiceStub, UnimplementedCloudSLAMServiceBase
from ....gen.app.cloudslam.v1.cloud_slam_pb2 import (
    CaptureInterval,
    EndStatus,
    GetActiveMappingSessionsForRobotRequest,
    GetActiveMappingSessionsForRobotResponse,
    GetMappingSessionMetadataByIDRequest,
    GetMappingSessionMetadataByIDResponse,
    GetMappingSessionPointCloudRequest,
    GetMappingSessionPointCloudResponse,
    ListMappingSessionsRequest,
    ListMappingSessionsResponse,
    MappingMetadata,
    Module,
    SensorInfo,
    StartMappingSessionRequest,
    StartMappingSessionResponse,
    StopMappingSessionRequest,
    StopMappingSessionResponse,
)

__all__ = [
    "CloudSLAMServiceBase",
    "CloudSLAMServiceStub",
    "UnimplementedCloudSLAMServiceBase",
    "CaptureInterval",
    "EndStatus",
    "GetActiveMappingSessionsForRobotRequest",
    "GetActiveMappingSessionsForRobotResponse",
    "GetMappingSessionMetadataByIDRequest",
    "GetMappingSessionMetadataByIDResponse",
    "GetMappingSessionPointCloudRequest",
    "GetMappingSessionPointCloudResponse",
    "ListMappingSessionsRequest",
    "ListMappingSessionsResponse",
    "MappingMetadata",
    "Module",
    "SensorInfo",
    "StartMappingSessionRequest",
    "StartMappingSessionResponse",
    "StopMappingSessionRequest",
    "StopMappingSessionResponse",
]
