"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.app.cloudslam.v1.cloud_slam_grpc import CloudSLAMServiceBase, CloudSLAMServiceStub
from ....gen.app.cloudslam.v1.cloud_slam_pb2 import (
    GetActiveMappingSessionsForRobotRequest,
    GetActiveMappingSessionsForRobotResponse,
    GetMappingSessionPointCloudRequest,
    GetMappingSessionPointCloudResponse,
    ListMappingSessionsRequest,
    ListMappingSessionsResponse,
    MappingMetadata,
    StartMappingSessionRequest,
    StartMappingSessionResponse,
    StopMappingSessionRequest,
    StopMappingSessionResponse,
)

__all__ = [
    "CloudSLAMServiceBase",
    "CloudSLAMServiceStub",
    "GetActiveMappingSessionsForRobotRequest",
    "GetActiveMappingSessionsForRobotResponse",
    "GetMappingSessionPointCloudRequest",
    "GetMappingSessionPointCloudResponse",
    "ListMappingSessionsRequest",
    "ListMappingSessionsResponse",
    "MappingMetadata",
    "StartMappingSessionRequest",
    "StartMappingSessionResponse",
    "StopMappingSessionRequest",
    "StopMappingSessionResponse",
]
