"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.app.cloudslam.v1.cloud_slam_unimplemented_grpc import UnimplementedCloudSLAMServiceBase

__all__ = [
    "UnimplementedCloudSLAMServiceBase",
]
