"""
@generated by Viam.
Do not edit manually!
"""

from ....gen.service.video.v1.video_grpc import UnimplementedVideoServiceBase, VideoServiceBase, VideoServiceStub
from ....gen.service.video.v1.video_pb2 import GetVideoRequest, GetVideoResponse

__all__ = [
    "UnimplementedVideoServiceBase",
    "VideoServiceBase",
    "VideoServiceStub",
    "GetVideoRequest",
    "GetVideoResponse",
]
