"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.proto.rpc.webrtc.v1.signaling_grpc import SignalingServiceBase, SignalingServiceStub
from ....gen.proto.rpc.webrtc.v1.signaling_pb2 import (
    AnswerRequest,
    AnswerRequestDoneStage,
    AnswerRequestErrorStage,
    AnswerRequestInitStage,
    AnswerRequestUpdateStage,
    AnswerResponse,
    AnswerResponseDoneStage,
    AnswerResponseErrorStage,
    AnswerResponseInitStage,
    AnswerResponseUpdateStage,
    CallRequest,
    CallResponse,
    CallResponseInitStage,
    CallResponseUpdateStage,
    CallUpdateRequest,
    CallUpdateResponse,
    ICECandidate,
    ICEServer,
    OptionalWebRTCConfigRequest,
    OptionalWebRTCConfigResponse,
    WebRTCConfig,
)

__all__ = [
    "SignalingServiceBase",
    "SignalingServiceStub",
    "AnswerRequest",
    "AnswerRequestDoneStage",
    "AnswerRequestErrorStage",
    "AnswerRequestInitStage",
    "AnswerRequestUpdateStage",
    "AnswerResponse",
    "AnswerResponseDoneStage",
    "AnswerResponseErrorStage",
    "AnswerResponseInitStage",
    "AnswerResponseUpdateStage",
    "CallRequest",
    "CallResponse",
    "CallResponseInitStage",
    "CallResponseUpdateStage",
    "CallUpdateRequest",
    "CallUpdateResponse",
    "ICECandidate",
    "ICEServer",
    "OptionalWebRTCConfigRequest",
    "OptionalWebRTCConfigResponse",
    "WebRTCConfig",
]
