"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.proto.rpc.webrtc.v1.signaling_unimplemented_grpc import UnimplementedSignalingServiceBase

__all__ = [
    "UnimplementedSignalingServiceBase",
]
