'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.service.datamanager.v1.data_manager_pb2 import (
    SensorData,
    SensorMetadata
)

__all__ = [
    'SensorData',
    'SensorMetadata',
]
