"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.arm.v1.arm_grpc import ArmServiceBase, ArmServiceStub
from ....gen.component.arm.v1.arm_pb2 import (
    GetEndPositionRequest,
    GetEndPositionResponse,
    GetJointPositionsRequest,
    GetJointPositionsResponse,
    IsMovingRequest,
    IsMovingResponse,
    JointPositions,
    MoveToJointPositionsRequest,
    MoveToJointPositionsResponse,
    MoveToPositionRequest,
    MoveToPositionResponse,
    Status,
    StopRequest,
    StopResponse,
)
from ....gen.component.arm.v1.arm_unimplemented_grpc import UnimplementedArmServiceBase

__all__ = [
    "ArmServiceBase",
    "ArmServiceStub",
    "GetEndPositionRequest",
    "GetEndPositionResponse",
    "GetJointPositionsRequest",
    "GetJointPositionsResponse",
    "IsMovingRequest",
    "IsMovingResponse",
    "JointPositions",
    "MoveToJointPositionsRequest",
    "MoveToJointPositionsResponse",
    "MoveToPositionRequest",
    "MoveToPositionResponse",
    "Status",
    "StopRequest",
    "StopResponse",
    "UnimplementedArmServiceBase",
]
