"""
@generated by Viam.
Do not edit manually!
"""

from ....gen.component.arm.v1.arm_grpc import ArmServiceBase, ArmServiceStub, UnimplementedArmServiceBase
from ....gen.component.arm.v1.arm_pb2 import (
    GetEndPositionRequest,
    GetEndPositionResponse,
    GetJointPositionsRequest,
    GetJointPositionsResponse,
    IsMovingRequest,
    IsMovingResponse,
    JointAccelerations,
    JointPositions,
    JointVelocities,
    MoveOptions,
    MoveThroughJointPositionsRequest,
    MoveThroughJointPositionsResponse,
    MoveThroughJointPositionsStreamedRequest,
    MoveThroughJointPositionsStreamedResponse,
    MoveToJointPositionsRequest,
    MoveToJointPositionsResponse,
    MoveToPositionRequest,
    MoveToPositionResponse,
    Status,
    StopRequest,
    StopResponse,
    TrajectoryPoint,
)

__all__ = [
    "ArmServiceBase",
    "ArmServiceStub",
    "UnimplementedArmServiceBase",
    "GetEndPositionRequest",
    "GetEndPositionResponse",
    "GetJointPositionsRequest",
    "GetJointPositionsResponse",
    "IsMovingRequest",
    "IsMovingResponse",
    "JointAccelerations",
    "JointPositions",
    "JointVelocities",
    "MoveOptions",
    "MoveThroughJointPositionsRequest",
    "MoveThroughJointPositionsResponse",
    "MoveThroughJointPositionsStreamedRequest",
    "MoveThroughJointPositionsStreamedResponse",
    "MoveToJointPositionsRequest",
    "MoveToJointPositionsResponse",
    "MoveToPositionRequest",
    "MoveToPositionResponse",
    "Status",
    "StopRequest",
    "StopResponse",
    "TrajectoryPoint",
]
