"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.powersensor.v1.powersensor_grpc import PowerSensorServiceBase, PowerSensorServiceStub
from ....gen.component.powersensor.v1.powersensor_pb2 import (
    GetCurrentRequest,
    GetCurrentResponse,
    GetPowerRequest,
    GetPowerResponse,
    GetVoltageRequest,
    GetVoltageResponse,
)
from ....gen.component.powersensor.v1.powersensor_unimplemented_grpc import UnimplementedPowerSensorServiceBase

__all__ = [
    "PowerSensorServiceBase",
    "PowerSensorServiceStub",
    "GetCurrentRequest",
    "GetCurrentResponse",
    "GetPowerRequest",
    "GetPowerResponse",
    "GetVoltageRequest",
    "GetVoltageResponse",
    "UnimplementedPowerSensorServiceBase",
]
