"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.powersensor.v1.powersensor_grpc import (
    PowerSensorServiceBase,
    PowerSensorServiceStub,
    UnimplementedPowerSensorServiceBase,
)
from ....gen.component.powersensor.v1.powersensor_pb2 import (
    GetCurrentRequest,
    GetCurrentResponse,
    GetPowerRequest,
    GetPowerResponse,
    GetVoltageRequest,
    GetVoltageResponse,
)

__all__ = [
    "PowerSensorServiceBase",
    "PowerSensorServiceStub",
    "UnimplementedPowerSensorServiceBase",
    "GetCurrentRequest",
    "GetCurrentResponse",
    "GetPowerRequest",
    "GetPowerResponse",
    "GetVoltageRequest",
    "GetVoltageResponse",
]
