"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.powersensor.v1.powersensor_unimplemented_grpc import UnimplementedPowerSensorServiceBase

__all__ = [
    "UnimplementedPowerSensorServiceBase",
]
