"""
@generated by Viam.
Do not edit manually!
"""
from .....gen.proto.rpc.examples.echoresource.v1.echoresource_unimplemented_grpc import UnimplementedEchoResourceServiceBase

__all__ = [
    "UnimplementedEchoResourceServiceBase",
]
