"""
@generated by Viam.
Do not edit manually!
"""

from ....gen.component.switch.v1.switch_grpc import SwitchServiceBase, SwitchServiceStub, UnimplementedSwitchServiceBase
from ....gen.component.switch.v1.switch_pb2 import (
    GetNumberOfPositionsRequest,
    GetNumberOfPositionsResponse,
    GetPositionRequest,
    GetPositionResponse,
    SetPositionRequest,
    SetPositionResponse,
)

__all__ = [
    "SwitchServiceBase",
    "SwitchServiceStub",
    "UnimplementedSwitchServiceBase",
    "GetNumberOfPositionsRequest",
    "GetNumberOfPositionsResponse",
    "GetPositionRequest",
    "GetPositionResponse",
    "SetPositionRequest",
    "SetPositionResponse",
]
