"""
@generated by Viam.
Do not edit manually!
"""
from ...gen.app.v1.end_user_grpc import EndUserServiceBase, EndUserServiceStub, UnimplementedEndUserServiceBase
from ...gen.app.v1.end_user_pb2 import (
    AcceptLegalRequest,
    AcceptLegalResponse,
    GetAuthApplicationRequest,
    GetAuthApplicationResponse,
    IsLegalAcceptedRequest,
    IsLegalAcceptedResponse,
    RegisterAuthApplicationRequest,
    RegisterAuthApplicationResponse,
    UpdateAuthApplicationRequest,
    UpdateAuthApplicationResponse,
)

__all__ = [
    "EndUserServiceBase",
    "EndUserServiceStub",
    "UnimplementedEndUserServiceBase",
    "AcceptLegalRequest",
    "AcceptLegalResponse",
    "GetAuthApplicationRequest",
    "GetAuthApplicationResponse",
    "IsLegalAcceptedRequest",
    "IsLegalAcceptedResponse",
    "RegisterAuthApplicationRequest",
    "RegisterAuthApplicationResponse",
    "UpdateAuthApplicationRequest",
    "UpdateAuthApplicationResponse",
]
