"""
@generated by Viam.
Do not edit manually!
"""
from ...gen.app.v1.end_user_grpc import EndUserServiceBase, EndUserServiceStub
from ...gen.app.v1.end_user_pb2 import (
    AcceptLegalRequest,
    AcceptLegalResponse,
    IsLegalAcceptedRequest,
    IsLegalAcceptedResponse,
    RegisterAuthApplicationRequest,
    RegisterAuthApplicationResponse,
    UpdateAuthApplicationRequest,
    UpdateAuthApplicationResponse,
)
from ...gen.app.v1.end_user_unimplemented_grpc import UnimplementedEndUserServiceBase

__all__ = [
    "EndUserServiceBase",
    "EndUserServiceStub",
    "AcceptLegalRequest",
    "AcceptLegalResponse",
    "IsLegalAcceptedRequest",
    "IsLegalAcceptedResponse",
    "RegisterAuthApplicationRequest",
    "RegisterAuthApplicationResponse",
    "UpdateAuthApplicationRequest",
    "UpdateAuthApplicationResponse",
    "UnimplementedEndUserServiceBase",
]
