"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.sensors.v1.sensors_grpc import SensorsServiceBase, SensorsServiceStub
from ....gen.service.sensors.v1.sensors_pb2 import GetReadingsRequest, GetReadingsResponse, GetSensorsRequest, GetSensorsResponse, Readings
from ....gen.service.sensors.v1.sensors_unimplemented_grpc import UnimplementedSensorsServiceBase

__all__ = [
    "SensorsServiceBase",
    "SensorsServiceStub",
    "GetReadingsRequest",
    "GetReadingsResponse",
    "GetSensorsRequest",
    "GetSensorsResponse",
    "Readings",
    "UnimplementedSensorsServiceBase",
]
