"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.sensors.v1.sensors_unimplemented_grpc import UnimplementedSensorsServiceBase

__all__ = [
    "UnimplementedSensorsServiceBase",
]
