"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.encoder.v1.encoder_unimplemented_grpc import UnimplementedEncoderServiceBase

__all__ = [
    "UnimplementedEncoderServiceBase",
]
