"""
@generated by Viam.
Do not edit manually!
"""

from ....gen.component.audioin.v1.audioin_grpc import AudioInServiceBase, AudioInServiceStub, UnimplementedAudioInServiceBase
from ....gen.component.audioin.v1.audioin_pb2 import AudioChunk, GetAudioRequest, GetAudioResponse

__all__ = [
    "AudioInServiceBase",
    "AudioInServiceStub",
    "UnimplementedAudioInServiceBase",
    "AudioChunk",
    "GetAudioRequest",
    "GetAudioResponse",
]
