"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.gantry.v1.gantry_grpc import GantryServiceBase, GantryServiceStub
from ....gen.component.gantry.v1.gantry_pb2 import (
    GetLengthsRequest,
    GetLengthsResponse,
    GetPositionRequest,
    GetPositionResponse,
    MoveToPositionRequest,
    MoveToPositionResponse,
    Status,
    StopRequest,
    StopResponse,
)

__all__ = [
    "GantryServiceBase",
    "GantryServiceStub",
    "GetLengthsRequest",
    "GetLengthsResponse",
    "GetPositionRequest",
    "GetPositionResponse",
    "MoveToPositionRequest",
    "MoveToPositionResponse",
    "Status",
    "StopRequest",
    "StopResponse",
]
