"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.gantry.v1.gantry_grpc import GantryServiceBase, GantryServiceStub
from ....gen.component.gantry.v1.gantry_pb2 import (
    GetLengthsRequest,
    GetLengthsResponse,
    GetPositionRequest,
    GetPositionResponse,
    HomeRequest,
    HomeResponse,
    IsMovingRequest,
    IsMovingResponse,
    MoveToPositionRequest,
    MoveToPositionResponse,
    Status,
    StopRequest,
    StopResponse,
)
from ....gen.component.gantry.v1.gantry_unimplemented_grpc import UnimplementedGantryServiceBase

__all__ = [
    "GantryServiceBase",
    "GantryServiceStub",
    "GetLengthsRequest",
    "GetLengthsResponse",
    "GetPositionRequest",
    "GetPositionResponse",
    "HomeRequest",
    "HomeResponse",
    "IsMovingRequest",
    "IsMovingResponse",
    "MoveToPositionRequest",
    "MoveToPositionResponse",
    "Status",
    "StopRequest",
    "StopResponse",
    "UnimplementedGantryServiceBase",
]
