"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.gantry.v1.gantry_unimplemented_grpc import UnimplementedGantryServiceBase

__all__ = [
    "UnimplementedGantryServiceBase",
]
