'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.service.framesystem.v1.frame_system_grpc import (
    FrameSystemServiceBase,
    FrameSystemServiceStub
)
from .....gen.proto.api.service.framesystem.v1.frame_system_pb2 import (
    Config,
    ConfigRequest,
    ConfigResponse,
    TransformPoseRequest,
    TransformPoseResponse
)

__all__ = [
    'FrameSystemServiceBase',
    'FrameSystemServiceStub',
    'Config',
    'ConfigRequest',
    'ConfigResponse',
    'TransformPoseRequest',
    'TransformPoseResponse',
]
