"""
@generated by Viam.
Do not edit manually!
"""

from .....gen.opentelemetry.proto.common.v1.common_pb2 import AnyValue, ArrayValue, EntityRef, InstrumentationScope, KeyValue, KeyValueList

__all__ = [
    "AnyValue",
    "ArrayValue",
    "EntityRef",
    "InstrumentationScope",
    "KeyValue",
    "KeyValueList",
]
