"""
@generated by Viam.
Do not edit manually!
"""
from .....gen.proto.api.component.motor.v1.motor_grpc import MotorServiceBase, MotorServiceStub
from .....gen.proto.api.component.motor.v1.motor_pb2 import (
    GetFeaturesRequest,
    GetFeaturesResponse,
    GetPositionRequest,
    GetPositionResponse,
    GoForRequest,
    GoForResponse,
    GoToRequest,
    GoToResponse,
    IsPoweredRequest,
    IsPoweredResponse,
    ResetZeroPositionRequest,
    ResetZeroPositionResponse,
    SetPowerRequest,
    SetPowerResponse,
    Status,
    StopRequest,
    StopResponse,
)

__all__ = [
    "MotorServiceBase",
    "MotorServiceStub",
    "GetFeaturesRequest",
    "GetFeaturesResponse",
    "GetPositionRequest",
    "GetPositionResponse",
    "GoForRequest",
    "GoForResponse",
    "GoToRequest",
    "GoToResponse",
    "IsPoweredRequest",
    "IsPoweredResponse",
    "ResetZeroPositionRequest",
    "ResetZeroPositionResponse",
    "SetPowerRequest",
    "SetPowerResponse",
    "Status",
    "StopRequest",
    "StopResponse",
]
