"""
@generated by Viam.
Do not edit manually!
"""

from ....gen.app.mlinference.v1.ml_inference_grpc import MLInferenceServiceBase, MLInferenceServiceStub, UnimplementedMLInferenceServiceBase
from ....gen.app.mlinference.v1.ml_inference_pb2 import GetInferenceRequest, GetInferenceResponse

__all__ = [
    "MLInferenceServiceBase",
    "MLInferenceServiceStub",
    "UnimplementedMLInferenceServiceBase",
    "GetInferenceRequest",
    "GetInferenceResponse",
]
