"""
@generated by Viam.
Do not edit manually!
"""
from .....gen.proto.api.component.sensor.v1.sensor_grpc import SensorServiceBase, SensorServiceStub
from .....gen.proto.api.component.sensor.v1.sensor_pb2 import GetReadingsRequest, GetReadingsResponse

__all__ = [
    "SensorServiceBase",
    "SensorServiceStub",
    "GetReadingsRequest",
    "GetReadingsResponse",
]
