"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.base.v1.base_grpc import BaseServiceBase, BaseServiceStub
from ....gen.component.base.v1.base_pb2 import (
    MoveStraightRequest,
    MoveStraightResponse,
    SetPowerRequest,
    SetPowerResponse,
    SetVelocityRequest,
    SetVelocityResponse,
    SpinRequest,
    SpinResponse,
    StopRequest,
    StopResponse,
)

__all__ = [
    "BaseServiceBase",
    "BaseServiceStub",
    "MoveStraightRequest",
    "MoveStraightResponse",
    "SetPowerRequest",
    "SetPowerResponse",
    "SetVelocityRequest",
    "SetVelocityResponse",
    "SpinRequest",
    "SpinResponse",
    "StopRequest",
    "StopResponse",
]
