"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.app.packages.v1.packages_unimplemented_grpc import UnimplementedPackageServiceBase

__all__ = [
    "UnimplementedPackageServiceBase",
]
