'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.component.camera.v1.camera_grpc import (
    CameraServiceBase,
    CameraServiceStub
)
from .....gen.proto.api.component.camera.v1.camera_pb2 import (
    GetFrameRequest,
    GetFrameResponse,
    GetPointCloudRequest,
    GetPointCloudResponse,
    Property,
    RenderFrameRequest,
    Video,
    Webcam,
    Webcams
)

__all__ = [
    'CameraServiceBase',
    'CameraServiceStub',
    'GetFrameRequest',
    'GetFrameResponse',
    'GetPointCloudRequest',
    'GetPointCloudResponse',
    'Property',
    'RenderFrameRequest',
    'Video',
    'Webcam',
    'Webcams',
]
