"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.app.model.v1.model_grpc import ModelServiceBase, ModelServiceStub
from ....gen.app.model.v1.model_pb2 import (
    DeleteRequest,
    DeleteResponse,
    DeployRequest,
    DeployResponse,
    File,
    FileData,
    InfoRequest,
    InfoResponse,
    Model,
    Status,
    SyncedModel,
    UploadMetadata,
    UploadRequest,
    UploadResponse,
)

__all__ = [
    "ModelServiceBase",
    "ModelServiceStub",
    "DeleteRequest",
    "DeleteResponse",
    "DeployRequest",
    "DeployResponse",
    "File",
    "FileData",
    "InfoRequest",
    "InfoResponse",
    "Model",
    "Status",
    "SyncedModel",
    "UploadMetadata",
    "UploadRequest",
    "UploadResponse",
]
