"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.app.model.v1.model_grpc import ModelServiceBase, ModelServiceStub
from ....gen.app.model.v1.model_pb2 import (
    DeleteMetadata,
    DeleteRequest,
    DeleteResponse,
    DeployMetadata,
    DeployRequest,
    DeployResponse,
    FileData,
    SyncedModel,
    UploadMetadata,
    UploadRequest,
    UploadResponse,
)

__all__ = [
    "ModelServiceBase",
    "ModelServiceStub",
    "DeleteMetadata",
    "DeleteRequest",
    "DeleteResponse",
    "DeployMetadata",
    "DeployRequest",
    "DeployResponse",
    "FileData",
    "SyncedModel",
    "UploadMetadata",
    "UploadRequest",
    "UploadResponse",
]
