"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.motion.v1.motion_grpc import MotionServiceBase, MotionServiceStub
from ....gen.service.motion.v1.motion_pb2 import (
    GetPoseRequest,
    GetPoseResponse,
    MoveRequest,
    MoveResponse,
    MoveSingleComponentRequest,
    MoveSingleComponentResponse,
)

__all__ = [
    "MotionServiceBase",
    "MotionServiceStub",
    "GetPoseRequest",
    "GetPoseResponse",
    "MoveRequest",
    "MoveResponse",
    "MoveSingleComponentRequest",
    "MoveSingleComponentResponse",
]
