"""
@generated by Viam.
Do not edit manually!
"""
from .....gen.proto.api.component.gripper.v1.gripper_grpc import GripperServiceBase, GripperServiceStub
from .....gen.proto.api.component.gripper.v1.gripper_pb2 import (
    GrabRequest,
    GrabResponse,
    OpenRequest,
    OpenResponse,
    StopRequest,
    StopResponse,
)

__all__ = [
    "GripperServiceBase",
    "GripperServiceStub",
    "GrabRequest",
    "GrabResponse",
    "OpenRequest",
    "OpenResponse",
    "StopRequest",
    "StopResponse",
]
