'''
@generated by Viam.
Do not edit manually!
'''
from ....gen.component.board.v1.board_grpc import (
    BoardServiceBase,
    BoardServiceStub,
    UnimplementedBoardServiceBase
)
from ....gen.component.board.v1.board_pb2 import (
    GetDigitalInterruptValueRequest,
    GetDigitalInterruptValueResponse,
    GetGPIORequest,
    GetGPIOResponse,
    PWMFrequencyRequest,
    PWMFrequencyResponse,
    PWMRequest,
    PWMResponse,
    PowerMode,
    ReadAnalogReaderRequest,
    ReadAnalogReaderResponse,
    SetGPIORequest,
    SetGPIOResponse,
    SetPWMFrequencyRequest,
    SetPWMFrequencyResponse,
    SetPWMRequest,
    SetPWMResponse,
    SetPowerModeRequest,
    SetPowerModeResponse,
    Status,
    StreamTicksRequest,
    StreamTicksResponse,
    WriteAnalogRequest,
    WriteAnalogResponse
)

__all__ = [
    'BoardServiceBase',
    'BoardServiceStub',
    'UnimplementedBoardServiceBase',
    'GetDigitalInterruptValueRequest',
    'GetDigitalInterruptValueResponse',
    'GetGPIORequest',
    'GetGPIOResponse',
    'PWMFrequencyRequest',
    'PWMFrequencyResponse',
    'PWMRequest',
    'PWMResponse',
    'PowerMode',
    'ReadAnalogReaderRequest',
    'ReadAnalogReaderResponse',
    'SetGPIORequest',
    'SetGPIOResponse',
    'SetPWMFrequencyRequest',
    'SetPWMFrequencyResponse',
    'SetPWMRequest',
    'SetPWMResponse',
    'SetPowerModeRequest',
    'SetPowerModeResponse',
    'Status',
    'StreamTicksRequest',
    'StreamTicksResponse',
    'WriteAnalogRequest',
    'WriteAnalogResponse',
]
