"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.board.v1.board_grpc import BoardServiceBase, BoardServiceStub
from ....gen.component.board.v1.board_pb2 import (
    GetDigitalInterruptValueRequest,
    GetDigitalInterruptValueResponse,
    GetGPIORequest,
    GetGPIOResponse,
    PWMFrequencyRequest,
    PWMFrequencyResponse,
    PWMRequest,
    PWMResponse,
    ReadAnalogReaderRequest,
    ReadAnalogReaderResponse,
    SetGPIORequest,
    SetGPIOResponse,
    SetPWMFrequencyRequest,
    SetPWMFrequencyResponse,
    SetPWMRequest,
    SetPWMResponse,
    StatusRequest,
    StatusResponse,
)

__all__ = [
    "BoardServiceBase",
    "BoardServiceStub",
    "GetDigitalInterruptValueRequest",
    "GetDigitalInterruptValueResponse",
    "GetGPIORequest",
    "GetGPIOResponse",
    "PWMFrequencyRequest",
    "PWMFrequencyResponse",
    "PWMRequest",
    "PWMResponse",
    "ReadAnalogReaderRequest",
    "ReadAnalogReaderResponse",
    "SetGPIORequest",
    "SetGPIOResponse",
    "SetPWMFrequencyRequest",
    "SetPWMFrequencyResponse",
    "SetPWMRequest",
    "SetPWMResponse",
    "StatusRequest",
    "StatusResponse",
]
