'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.component.gps.v1.gps_grpc import (
    GPSServiceBase,
    GPSServiceStub
)
from .....gen.proto.api.component.gps.v1.gps_pb2 import (
    ReadAltitudeRequest,
    ReadAltitudeResponse,
    ReadLocationRequest,
    ReadLocationResponse,
    ReadSpeedRequest,
    ReadSpeedResponse
)

__all__ = [
    'GPSServiceBase',
    'GPSServiceStub',
    'ReadAltitudeRequest',
    'ReadAltitudeResponse',
    'ReadLocationRequest',
    'ReadLocationResponse',
    'ReadSpeedRequest',
    'ReadSpeedResponse',
]
