"""
@generated by Viam.
Do not edit manually!
"""

from ....gen.service.discovery.v1.discovery_grpc import DiscoveryServiceBase, DiscoveryServiceStub, UnimplementedDiscoveryServiceBase
from ....gen.service.discovery.v1.discovery_pb2 import DiscoverResourcesRequest, DiscoverResourcesResponse

__all__ = [
    "DiscoveryServiceBase",
    "DiscoveryServiceStub",
    "UnimplementedDiscoveryServiceBase",
    "DiscoverResourcesRequest",
    "DiscoverResourcesResponse",
]
