"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.movementsensor.v1.movementsensor_unimplemented_grpc import UnimplementedMovementSensorServiceBase

__all__ = [
    "UnimplementedMovementSensorServiceBase",
]
