"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.slam.v1.slam_grpc import SLAMServiceBase, SLAMServiceStub
from ....gen.service.slam.v1.slam_pb2 import (
    GetInternalStateRequest,
    GetInternalStateResponse,
    GetPointCloudMapRequest,
    GetPointCloudMapResponse,
    GetPositionRequest,
    GetPositionResponse,
    GetPropertiesRequest,
    GetPropertiesResponse,
    MappingMode,
)

__all__ = [
    "SLAMServiceBase",
    "SLAMServiceStub",
    "GetInternalStateRequest",
    "GetInternalStateResponse",
    "GetPointCloudMapRequest",
    "GetPointCloudMapResponse",
    "GetPositionRequest",
    "GetPositionResponse",
    "GetPropertiesRequest",
    "GetPropertiesResponse",
    "MappingMode",
]
