"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.slam.v1.slam_grpc import SLAMServiceBase, SLAMServiceStub
from ....gen.service.slam.v1.slam_pb2 import GetMapRequest, GetMapResponse, GetPositionRequest, GetPositionResponse

__all__ = [
    "SLAMServiceBase",
    "SLAMServiceStub",
    "GetMapRequest",
    "GetMapResponse",
    "GetPositionRequest",
    "GetPositionResponse",
]
