"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.slam.v1.slam_grpc import SLAMServiceBase, SLAMServiceStub
from ....gen.service.slam.v1.slam_pb2 import (
    GetInternalStateRequest,
    GetInternalStateResponse,
    GetInternalStateStreamRequest,
    GetInternalStateStreamResponse,
    GetPointCloudMapRequest,
    GetPointCloudMapResponse,
    GetPointCloudMapStreamRequest,
    GetPointCloudMapStreamResponse,
    GetPositionNewRequest,
    GetPositionNewResponse,
    GetPositionRequest,
    GetPositionResponse,
)

__all__ = [
    "SLAMServiceBase",
    "SLAMServiceStub",
    "GetInternalStateRequest",
    "GetInternalStateResponse",
    "GetInternalStateStreamRequest",
    "GetInternalStateStreamResponse",
    "GetPointCloudMapRequest",
    "GetPointCloudMapResponse",
    "GetPointCloudMapStreamRequest",
    "GetPointCloudMapStreamResponse",
    "GetPositionNewRequest",
    "GetPositionNewResponse",
    "GetPositionRequest",
    "GetPositionResponse",
]
