"""
@generated by Viam.
Do not edit manually!
"""
from ...gen.stream.v1.stream_grpc import StreamServiceBase, StreamServiceStub, UnimplementedStreamServiceBase
from ...gen.stream.v1.stream_pb2 import (
    AddStreamRequest,
    AddStreamResponse,
    ListStreamsRequest,
    ListStreamsResponse,
    RemoveStreamRequest,
    RemoveStreamResponse,
)

__all__ = [
    "StreamServiceBase",
    "StreamServiceStub",
    "UnimplementedStreamServiceBase",
    "AddStreamRequest",
    "AddStreamResponse",
    "ListStreamsRequest",
    "ListStreamsResponse",
    "RemoveStreamRequest",
    "RemoveStreamResponse",
]
