'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.service.objectsegmentation.v1.object_segmentation_grpc import (
    ObjectSegmentationServiceBase,
    ObjectSegmentationServiceStub
)
from .....gen.proto.api.service.objectsegmentation.v1.object_segmentation_pb2 import (
    GetObjectPointCloudsRequest,
    GetObjectPointCloudsResponse,
    GetSegmenterParametersRequest,
    GetSegmenterParametersResponse,
    GetSegmentersRequest,
    GetSegmentersResponse,
    TypedParameter
)

__all__ = [
    'ObjectSegmentationServiceBase',
    'ObjectSegmentationServiceStub',
    'GetObjectPointCloudsRequest',
    'GetObjectPointCloudsResponse',
    'GetSegmenterParametersRequest',
    'GetSegmenterParametersResponse',
    'GetSegmentersRequest',
    'GetSegmentersResponse',
    'TypedParameter',
]
