"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.mlmodel.v1.mlmodel_grpc import MLModelServiceBase, MLModelServiceStub
from ....gen.service.mlmodel.v1.mlmodel_pb2 import (
    File,
    InferRequest,
    InferResponse,
    LabelType,
    Metadata,
    MetadataRequest,
    MetadataResponse,
    TensorInfo,
)

__all__ = [
    "MLModelServiceBase",
    "MLModelServiceStub",
    "File",
    "InferRequest",
    "InferResponse",
    "LabelType",
    "Metadata",
    "MetadataRequest",
    "MetadataResponse",
    "TensorInfo",
]
