"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.mlmodel.v1.mlmodel_grpc import MLModelServiceBase, MLModelServiceStub, UnimplementedMLModelServiceBase
from ....gen.service.mlmodel.v1.mlmodel_pb2 import (
    File,
    FlatTensor,
    FlatTensorDataDouble,
    FlatTensorDataFloat,
    FlatTensorDataInt8,
    FlatTensorDataInt16,
    FlatTensorDataInt32,
    FlatTensorDataInt64,
    FlatTensorDataUInt8,
    FlatTensorDataUInt16,
    FlatTensorDataUInt32,
    FlatTensorDataUInt64,
    FlatTensors,
    InferRequest,
    InferResponse,
    LabelType,
    Metadata,
    MetadataRequest,
    MetadataResponse,
    TensorInfo,
)

__all__ = [
    "MLModelServiceBase",
    "MLModelServiceStub",
    "UnimplementedMLModelServiceBase",
    "File",
    "FlatTensor",
    "FlatTensorDataDouble",
    "FlatTensorDataFloat",
    "FlatTensorDataInt16",
    "FlatTensorDataInt32",
    "FlatTensorDataInt64",
    "FlatTensorDataInt8",
    "FlatTensorDataUInt16",
    "FlatTensorDataUInt32",
    "FlatTensorDataUInt64",
    "FlatTensorDataUInt8",
    "FlatTensors",
    "InferRequest",
    "InferResponse",
    "LabelType",
    "Metadata",
    "MetadataRequest",
    "MetadataResponse",
    "TensorInfo",
]
