"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.mlmodel.v1.mlmodel_unimplemented_grpc import UnimplementedMLModelServiceBase

__all__ = [
    "UnimplementedMLModelServiceBase",
]
