"""
@generated by Viam.
Do not edit manually!
"""

from ....gen.component.audioout.v1.audioout_grpc import AudioOutServiceBase, AudioOutServiceStub, UnimplementedAudioOutServiceBase
from ....gen.component.audioout.v1.audioout_pb2 import (
    PlayRequest,
    PlayResponse,
    PlayStreamChunk,
    PlayStreamInit,
    PlayStreamRequest,
    PlayStreamResponse,
)

__all__ = [
    "AudioOutServiceBase",
    "AudioOutServiceStub",
    "UnimplementedAudioOutServiceBase",
    "PlayRequest",
    "PlayResponse",
    "PlayStreamChunk",
    "PlayStreamInit",
    "PlayStreamRequest",
    "PlayStreamResponse",
]
