'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.service.sensors.v1.sensors_grpc import (
    SensorsServiceBase,
    SensorsServiceStub
)
from .....gen.proto.api.service.sensors.v1.sensors_pb2 import (
    GetReadingsRequest,
    GetReadingsResponse,
    GetSensorsRequest,
    GetSensorsResponse,
    Readings
)

__all__ = [
    'SensorsServiceBase',
    'SensorsServiceStub',
    'GetReadingsRequest',
    'GetReadingsResponse',
    'GetSensorsRequest',
    'GetSensorsResponse',
    'Readings',
]
