"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.audioinput.v1.audioinput_grpc import AudioInputServiceBase, AudioInputServiceStub, UnimplementedAudioInputServiceBase
from ....gen.component.audioinput.v1.audioinput_pb2 import (
    AudioChunk,
    AudioChunkInfo,
    ChunksRequest,
    ChunksResponse,
    PropertiesRequest,
    PropertiesResponse,
    RecordRequest,
    SampleFormat,
)

__all__ = [
    "AudioInputServiceBase",
    "AudioInputServiceStub",
    "UnimplementedAudioInputServiceBase",
    "AudioChunk",
    "AudioChunkInfo",
    "ChunksRequest",
    "ChunksResponse",
    "PropertiesRequest",
    "PropertiesResponse",
    "RecordRequest",
    "SampleFormat",
]
