"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.audioinput.v1.audioinput_grpc import AudioInputServiceBase, AudioInputServiceStub
from ....gen.component.audioinput.v1.audioinput_pb2 import (
    AudioChunk,
    AudioChunkInfo,
    ChunksRequest,
    ChunksResponse,
    PropertiesRequest,
    PropertiesResponse,
    RecordRequest,
)

__all__ = [
    "AudioInputServiceBase",
    "AudioInputServiceStub",
    "AudioChunk",
    "AudioChunkInfo",
    "ChunksRequest",
    "ChunksResponse",
    "PropertiesRequest",
    "PropertiesResponse",
    "RecordRequest",
]
