"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.audioinput.v1.audioinput_unimplemented_grpc import UnimplementedAudioInputServiceBase

__all__ = [
    "UnimplementedAudioInputServiceBase",
]
