"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.testecho.v1.testecho_grpc import TestEchoServiceBase, TestEchoServiceStub, UnimplementedTestEchoServiceBase
from ....gen.component.testecho.v1.testecho_pb2 import (
    EchoBiDiRequest,
    EchoBiDiResponse,
    EchoMultipleRequest,
    EchoMultipleResponse,
    EchoRequest,
    EchoResponse,
    StopRequest,
    StopResponse,
)

__all__ = [
    "TestEchoServiceBase",
    "TestEchoServiceStub",
    "UnimplementedTestEchoServiceBase",
    "EchoBiDiRequest",
    "EchoBiDiResponse",
    "EchoMultipleRequest",
    "EchoMultipleResponse",
    "EchoRequest",
    "EchoResponse",
    "StopRequest",
    "StopResponse",
]
