"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.testecho.v1.testecho_unimplemented_grpc import UnimplementedTestEchoServiceBase

__all__ = [
    "UnimplementedTestEchoServiceBase",
]
