"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.sensor.v1.sensor_grpc import SensorServiceBase, SensorServiceStub, UnimplementedSensorServiceBase

__all__ = [
    "SensorServiceBase",
    "SensorServiceStub",
    "UnimplementedSensorServiceBase",
]
