"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.sensor.v1.sensor_unimplemented_grpc import UnimplementedSensorServiceBase

__all__ = [
    "UnimplementedSensorServiceBase",
]
