"""
@generated by Viam.
Do not edit manually!
"""

from .....gen.opentelemetry.proto.trace.v1.trace_pb2 import ResourceSpans, ScopeSpans, Span, SpanFlags, Status, TracesData

__all__ = [
    "ResourceSpans",
    "ScopeSpans",
    "Span",
    "SpanFlags",
    "Status",
    "TracesData",
]
