'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.component.servo.v1.servo_grpc import (
    ServoServiceBase,
    ServoServiceStub
)
from .....gen.proto.api.component.servo.v1.servo_pb2 import (
    GetPositionRequest,
    GetPositionResponse,
    MoveRequest,
    MoveResponse,
    Status
)

__all__ = [
    'ServoServiceBase',
    'ServoServiceStub',
    'GetPositionRequest',
    'GetPositionResponse',
    'MoveRequest',
    'MoveResponse',
    'Status',
]
