# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/summation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19src/proto/summation.proto\x12\x19\x61\x63me.service.summation.v1\x1a\x1cgoogle/api/annotations.proto\":\n\nSumRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n\x07numbers\x18\x02 \x03(\x01R\x07numbers\"\x1f\n\x0bSumResponse\x12\x10\n\x03sum\x18\x01 \x01(\x01R\x03sum2\x9c\x01\n\x10SummationService\x12\x87\x01\n\x03Sum\x12%.acme.service.summation.v1.SumRequest\x1a&.acme.service.summation.v1.SumResponse\"1\x82\xd3\xe4\x93\x02+\")/acme/api/v1/service/summation/{name}/sumb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.summation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMMATIONSERVICE.methods_by_name['Sum']._options = None
  _SUMMATIONSERVICE.methods_by_name['Sum']._serialized_options = b'\202\323\344\223\002+\")/acme/api/v1/service/summation/{name}/sum'
  _SUMREQUEST._serialized_start=86
  _SUMREQUEST._serialized_end=144
  _SUMRESPONSE._serialized_start=146
  _SUMRESPONSE._serialized_end=177
  _SUMMATIONSERVICE._serialized_start=180
  _SUMMATIONSERVICE._serialized_end=336
# @@protoc_insertion_point(module_scope)
