'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.component.forcematrix.v1.force_matrix_grpc import (
    ForceMatrixServiceBase,
    ForceMatrixServiceStub
)
from .....gen.proto.api.component.forcematrix.v1.force_matrix_pb2 import (
    DetectSlipRequest,
    DetectSlipResponse,
    Matrix,
    ReadMatrixRequest,
    ReadMatrixResponse
)

__all__ = [
    'ForceMatrixServiceBase',
    'ForceMatrixServiceStub',
    'DetectSlipRequest',
    'DetectSlipResponse',
    'Matrix',
    'ReadMatrixRequest',
    'ReadMatrixResponse',
]
