'''
@generated by Viam.
Do not edit manually!
'''
from ....gen.proto.api.robot.v1.robot_grpc import (
    RobotServiceBase,
    RobotServiceStub
)
from ....gen.proto.api.robot.v1.robot_pb2 import (
    BlockForOperationRequest,
    BlockForOperationResponse,
    CancelOperationRequest,
    CancelOperationResponse,
    GetOperationsRequest,
    GetOperationsResponse,
    Operation
)

__all__ = [
    'RobotServiceBase',
    'RobotServiceStub',
    'BlockForOperationRequest',
    'BlockForOperationResponse',
    'CancelOperationRequest',
    'CancelOperationResponse',
    'GetOperationsRequest',
    'GetOperationsResponse',
    'Operation',
]
