'''
@generated by Viam.
Do not edit manually!
'''
from ....gen.proto.api.robot.v1.robot_grpc import (
    RobotServiceBase,
    RobotServiceStub
)
from ....gen.proto.api.robot.v1.robot_pb2 import (
    BlockForOperationRequest,
    BlockForOperationResponse,
    CancelOperationRequest,
    CancelOperationResponse,
    FrameSystemConfig,
    FrameSystemConfigRequest,
    FrameSystemConfigResponse,
    GetOperationsRequest,
    GetOperationsResponse,
    Operation,
    ResourceNamesRequest,
    ResourceNamesResponse,
    TransformPoseRequest,
    TransformPoseResponse
)

__all__ = [
    'RobotServiceBase',
    'RobotServiceStub',
    'BlockForOperationRequest',
    'BlockForOperationResponse',
    'CancelOperationRequest',
    'CancelOperationResponse',
    'FrameSystemConfig',
    'FrameSystemConfigRequest',
    'FrameSystemConfigResponse',
    'GetOperationsRequest',
    'GetOperationsResponse',
    'Operation',
    'ResourceNamesRequest',
    'ResourceNamesResponse',
    'TransformPoseRequest',
    'TransformPoseResponse',
]
