'''
**** THIS IS A GENERATED FILE ****
********** DO NOT EDIT ***********
'''
from ....gen.proto.api.robot.v1.robot_grpc import (
    RobotServiceBase,
    RobotServiceStub
)
from ....gen.proto.api.robot.v1.robot_pb2 import (
    ArmStatus,
    ComponentConfig,
    ConfigRequest,
    ConfigResponse,
    DoActionRequest,
    DoActionResponse,
    ExecuteFunctionRequest,
    ExecuteFunctionResponse,
    ExecuteSourceRequest,
    ExecuteSourceResponse,
    GantryStatus,
    InputControllerEvent,
    InputControllerStatus,
    JointPositions,
    MotorStatus,
    NavigationServiceAddWaypointRequest,
    NavigationServiceAddWaypointResponse,
    NavigationServiceLocationRequest,
    NavigationServiceLocationResponse,
    NavigationServiceModeRequest,
    NavigationServiceModeResponse,
    NavigationServiceRemoveWaypointRequest,
    NavigationServiceRemoveWaypointResponse,
    NavigationServiceSetModeRequest,
    NavigationServiceSetModeResponse,
    NavigationServiceWaypoint,
    NavigationServiceWaypointsRequest,
    NavigationServiceWaypointsResponse,
    Pose,
    ResourceRunCommandRequest,
    ResourceRunCommandResponse,
    SensorReadingsRequest,
    SensorReadingsResponse,
    SensorStatus,
    ServoStatus,
    Status,
    StatusRequest,
    StatusResponse,
    StatusStreamRequest,
    StatusStreamResponse
)
