"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.generic.v1.generic_grpc import GenericServiceBase, GenericServiceStub
from ....gen.component.generic.v1.generic_unimplemented_grpc import UnimplementedGenericServiceBase

__all__ = [
    "GenericServiceBase",
    "GenericServiceStub",
    "UnimplementedGenericServiceBase",
]
