"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.generic.v1.generic_grpc import GenericServiceBase, GenericServiceStub
from ....gen.component.generic.v1.generic_pb2 import DoCommandRequest, DoCommandResponse

__all__ = [
    "GenericServiceBase",
    "GenericServiceStub",
    "DoCommandRequest",
    "DoCommandResponse",
]
