"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.component.generic.v1.generic_grpc import GenericServiceBase, GenericServiceStub

__all__ = [
    "GenericServiceBase",
    "GenericServiceStub",
]
