"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.app.agent.v1.agent_grpc import AgentAppServiceBase, AgentAppServiceStub, AgentDeviceServiceBase, AgentDeviceServiceStub
from ....gen.app.agent.v1.agent_pb2 import (
    AppAgentConfig,
    AppSubsystemConfig,
    DeviceAgentConfigRequest,
    DeviceAgentConfigResponse,
    DeviceSubsystemConfig,
    GetAgentConfigRequest,
    GetAgentConfigResponse,
    HostInfo,
    PackageFormat,
    SubsystemUpdateInfo,
    UpdateAgentConfigRequest,
    UpdateAgentConfigResponse,
)
from ....gen.app.agent.v1.agent_unimplemented_grpc import UnimplementedAgentAppServiceBase, UnimplementedAgentDeviceServiceBase

__all__ = [
    "AgentAppServiceBase",
    "AgentAppServiceStub",
    "AgentDeviceServiceBase",
    "AgentDeviceServiceStub",
    "AppAgentConfig",
    "AppSubsystemConfig",
    "DeviceAgentConfigRequest",
    "DeviceAgentConfigResponse",
    "DeviceSubsystemConfig",
    "GetAgentConfigRequest",
    "GetAgentConfigResponse",
    "HostInfo",
    "PackageFormat",
    "SubsystemUpdateInfo",
    "UpdateAgentConfigRequest",
    "UpdateAgentConfigResponse",
    "UnimplementedAgentAppServiceBase",
    "UnimplementedAgentDeviceServiceBase",
]
