"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.app.agent.v1.agent_grpc import AgentDeviceServiceBase, AgentDeviceServiceStub, UnimplementedAgentDeviceServiceBase
from ....gen.app.agent.v1.agent_pb2 import (
    DeviceAgentConfigRequest,
    DeviceAgentConfigResponse,
    DeviceSubsystemConfig,
    HostInfo,
    PackageFormat,
    SubsystemUpdateInfo,
)

__all__ = [
    "AgentDeviceServiceBase",
    "AgentDeviceServiceStub",
    "UnimplementedAgentDeviceServiceBase",
    "DeviceAgentConfigRequest",
    "DeviceAgentConfigResponse",
    "DeviceSubsystemConfig",
    "HostInfo",
    "PackageFormat",
    "SubsystemUpdateInfo",
]
