"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.app.agent.v1.agent_unimplemented_grpc import UnimplementedAgentAppServiceBase, UnimplementedAgentDeviceServiceBase

__all__ = [
    "UnimplementedAgentAppServiceBase",
    "UnimplementedAgentDeviceServiceBase",
]
