'''
@generated by Viam.
Do not edit manually!
'''
from .....gen.proto.api.service.status.v1.status_grpc import (
    StatusServiceBase,
    StatusServiceStub
)
from .....gen.proto.api.service.status.v1.status_pb2 import (
    GetStatusRequest,
    GetStatusResponse,
    Status,
    StreamStatusRequest,
    StreamStatusResponse
)

__all__ = [
    'StatusServiceBase',
    'StatusServiceStub',
    'GetStatusRequest',
    'GetStatusResponse',
    'Status',
    'StreamStatusRequest',
    'StreamStatusResponse',
]
