"""
@generated by Viam.
Do not edit manually!
"""
from ....gen.service.generic.v1.generic_grpc import GenericServiceBase, GenericServiceStub, UnimplementedGenericServiceBase

__all__ = [
    "GenericServiceBase",
    "GenericServiceStub",
    "UnimplementedGenericServiceBase",
]
