name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    if: github.repository_owner == 'viamrobotics'
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64

    steps:
      - name: Check if organization member
        id: is_organization_member
        if: github.event_name == 'workflow_dispatch'
        uses: jamessingleton/is-organization-member@1.0.1
        with:
          organization: viamrobotics
          username: ${{ github.actor }}
          token:  ${{ secrets.GITHUB_TOKEN }}

      - name: cancelling
        uses: andymckay/cancel-action@0.2
        if: |
          github.event_name == 'workflow_dispatch' && steps.is_organization_member.outputs.result == 'false'

      - name: Download Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "viam_sdk.*\\.whl"
          regex: true
          target: 'dist/'
          version: tags/${{ github.event.release.tag_name }}

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.23.0
        if: ${{ !contains(github.event.release.tag_name, 'rc') && !contains(github.event.release.tag_name, 'a') && !contains(github.event.release.tag_name, 'b')}}
        with:
          payload: |
            {
              "channel_id": "U02E1NSJG2J",
              "link": "https://github.com/viamrobotics/viam-python-sdk/releases/tag/${{ github.event.release.tag_name }}",
              "sdk_name": "Viam Python SDK",
              "version": "${{ github.event.release.tag_name }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
