name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    if: |
      github.repository_owner == 'viamrobotics'
      && (github.event_name == 'workflow_dispatch' || github.event_name == 'release')
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64

    steps:
      - name: Install the gh cli
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      - name: Install jq
        run: apt install jq -y

      - name: Get SDK/NetCode team members
        id: get-members
        uses: garnertb/get-team-members@v1
        with:
          org: viamrobotics
          team_slug: sdk-netcode
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: cancelling
        uses: andymckay/cancel-action@0.2
        if: |
          github.event_name == 'workflow_dispatch' && contains(fromJson(${{ steps.get-members.outputs.members }}), github.actor)

      - name: Download Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "viam_sdk.*\\.whl"
          regex: true
          target: 'dist/'

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
