name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    if: |
      github.repository_owner == 'viamrobotics'
      && github.ref == 'refs/heads/main'
      && ((github.event_name == 'workflow_dispatch' && contains(fromJson('["njooma"]'), github.actor)) || github.event_name == 'release')
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64

    steps:
      - name: Download Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "viam_sdk.*\\.whl"
          regex: true
          target: 'dist/'

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
