"""
@generated by Viam.
Do not edit manually!
"""
from ...gen.provisioning.v1.provisioning_grpc import ProvisioningServiceBase, ProvisioningServiceStub, UnimplementedProvisioningServiceBase
from ...gen.provisioning.v1.provisioning_pb2 import (
    CloudConfig,
    GetNetworkListRequest,
    GetNetworkListResponse,
    GetSmartMachineStatusRequest,
    GetSmartMachineStatusResponse,
    NetworkInfo,
    ProvisioningInfo,
    SetNetworkCredentialsRequest,
    SetNetworkCredentialsResponse,
    SetSmartMachineCredentialsRequest,
    SetSmartMachineCredentialsResponse,
)

__all__ = [
    "ProvisioningServiceBase",
    "ProvisioningServiceStub",
    "UnimplementedProvisioningServiceBase",
    "CloudConfig",
    "GetNetworkListRequest",
    "GetNetworkListResponse",
    "GetSmartMachineStatusRequest",
    "GetSmartMachineStatusResponse",
    "NetworkInfo",
    "ProvisioningInfo",
    "SetNetworkCredentialsRequest",
    "SetNetworkCredentialsResponse",
    "SetSmartMachineCredentialsRequest",
    "SetSmartMachineCredentialsResponse",
]
