"""
@generated by Viam.
Do not edit manually!
"""
from ...gen.provisioning.v1.provisioning_unimplemented_grpc import UnimplementedProvisioningServiceBase

__all__ = [
    "UnimplementedProvisioningServiceBase",
]
